version = 1

exclude_patterns = [
  "bbc_training/**"
]

test_patterns = [
  "test_*.py",
  "*_test.py"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
